"use strict";
exports.__esModule = true;
exports.EVENTS_CONST = {
    AFTER_ADD: "AFTER_ADD",
    AFTER_DELETE: "AFTER_DELETE",
    AFTER_EDIT: "AFTER_EDIT",
    AFTER_GET: "AFTER_GET",
    AFTER_SEARCH: "AFTER_SEARCH",
    BEFORE_ADD: "BEFORE_ADD",
    BEFORE_DELETE: "BEFORE_DELETE",
    BEFORE_EDIT: "BEFORE_EDIT",
    BEFORE_GET: "BEFORE_GET",
    BEFORE_SEARCH: "BEFORE_SEARCH"
};
exports.REPO_ACTIONS = {
    ADD: "ADD",
    DELETE: "DELETE",
    EDIT: "EDIT",
    GET: "GET",
    SEARCH: "SEARCH"
};
